version: '3.8'

networks:
  inception:
    name: inception

volumes:
  wordpress:
    driver_opts:
      type: none
      device: /home/jjaen-mo/volumes/wp
      o: bind
  mariadb:
    driver_opts:
      type: none
      device: /home/jjaen-mo/volumes/db
      o: bind

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx:42
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    depends_on:
      - wordpress
    restart: always

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress:42
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    ports:
      - "9000:9000"
    restart: always

  mariadb:
    container_name: mariadb
    build:
      args:
        - db_n=${db_n}
        - db_u=${db_u}
        - db_p=${db_p}
      context: ./requirements/mariadb
    image: mariadb:42
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always